---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/workers":
    get:
      summary: Get all workers
      tags:
      - Worker
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Authorization token
        schema:
          type: string
      responses:
        '200':
          description: workers found
        '401':
          description: unauthorized
    post:
      summary: Create a worker
      tags:
      - Worker
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Authorization token
        schema:
          type: string
      responses:
        '302':
          description: redirected
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                worker:
                  title:
                    type: string
                  body:
                    type: string
              required:
              - title
              - body
          application/xml:
            schema:
              type: object
              properties:
                worker:
                  title:
                    type: string
                  body:
                    type: string
              required:
              - title
              - body
  "/api/v1/workers/{id}":
    get:
      summary: Get a worker
      tags:
      - Worker
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Authorization token
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ID of the worker
        schema:
          type: string
      responses:
        '200':
          description: worker found
        '404':
          description: worker not found
        '401':
          description: unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
